FORMAT: 1A
HOST: http://greenpool-c9-rahulroy9202.c9.io

# GP
GP API is a *Commuter Social Network* service bringing people together.

# Group RealTime Location Services
Location Services of **GP API** available after login


## Set User Destination [/user/destination]
### destination location [POST]
+ Request (application/json)

        {"lat": 180, "long": 180 , "name": "end of the world"}
    
+ Response 200 (application/json)

        {"status": 2 , "comment": "destination_set" }


## Set User Current Location [/user/currloc]
### current location [POST]
+ Request (application/json)

        {"lat": 180, "long": 180 }

+ Response 200 (application/json)

        {"status": 200} 


## Get GreenPool Users in Proximity [/user/peers]
### return location array [POST]
+ Request (application/json)

        {"lat": 180, "long": 180 }

+ Response 200 (application/json)

        [
         {"userid": "aaaa1111", "location": {"lat": 177, "long": 177}},
         {"userid": "aaaa2222", "location": {"lat": 178, "long": 178}},
         {"userid": "aaaa3333", "location": {"lat": 179, "long": 179}},
         {"userid": "aaaa4444", "location": {"lat": 181, "long": 181}}
        ]


# Group Users
User related resources of the **GP API**

## User Authentication [/user]
### Login [GET]
+ Request (application/json)

        { "userid": "aaaa1111", "password#": "bbbb2222" }

+ Response 202 (application/json)
        
        { "status":"logged_in", "id": 2222 }


## User SignUp [/newuser]
### SignUp [POST]
+ Request (application/json)

        { "userid": "aaaa1111", "password#": "bbbb2222", "email": "test@example.com" }

+ Response 202 (application/json)
        
        { "status":"successfull", "id": 2222 }


## User Profile [/user/{id}]
### Get Profile Details [GET]
User selects a particular peer for details
+ Request (application/json)

        { "userid": "aaaa1111" } id of current user. will be used to log info of profile access.

+ Response 200 (application/json)

        { "userid": "aaaa2222", "destination": {"name":"end of world","lat": 180,"long": 180} }


## User Requesting Ride [/{id}/requestride/]
### RequestRide [POST]
+ Request (application/json)

        { "userid1": "aaaa1111", "userid2": "aaaa2222" } requesting user and requested user id

+ Response 202 (application/json)
        
        { "status":"pending", "requestid": 2222 }


## User Specific Ride Requests [/{id}/myrequests/]
### Get Ride Requests [GET]
+ Request (application/json)

        { "lastsynctime": "dateobject"} 

+ Response 202 (application/json)

        [{"userid": "a", "location": {"lat": 177, "long": 177}},
         {"userid": "b", "location": {"lat": 177, "long": 177}},
         {"userid": "c", "location": {"lat": 177, "long": 177}}]
         
         
         
         